export * from './ArrowNext'
export * from './ArrowPrev'
export * from './InstagramLogo'
export * from './MailLogo'
export * from './PlayTgLink'
export * from './RDLogo'
export * from './TelegramLogo'
export * from './VkLogo'
